### PR TITLE
add client/host requires

### PR DESCRIPTION
**Pull request by omsmith**
Allows a consumer to require('ifrau/client'), etc.

### CODE REVIEW

**Comment by omsmith** [comment]
Switching to _frau-jwt/client_ in _frau-jwt_ drops the bundle size from _62373_ to _36169_.

**Comment by dlockhart** [comment]
Any README.md implications?

**Comment by omsmith** [comment]
Probably could

**Comment by omsmith** [comment]
@dlockhart Note seem okay to you? Give they aren't available from the CDN, I just put them in as comments in the examples.

Next step would be to try to setup seperate client/host deployments to the cdn like you had going before.

**Comment by dlockhart** [comment]
Perfect, thanks!

**Pull request merged**
