### PR TITLE
feat: Empty commit to trigger release

### PR DESCRIPTION
**Pull request by EvanLemieux**
Forgot to prepend my merge with `feat:`

### CODE REVIEW

**Review by eKoopmans — APPROVED** [review]

**Comment by grant-cleary** [comment]
So I think pushing this as a `feat` release just made things a bit tricky because `ifrau` is in pre-release. I think you'll now need to coordinate updating every dependency that uses it in BSI to upgrade at the same time, otherwise trying to bump it in BSI alone will blow up the BSI build. 😅

**Comment by EvanLemieux** [comment]
> So I think pushing this as a `feat` release just made things a bit tricky because `ifrau` is in pre-release. I think you'll now need to coordinate updating every dependency that uses it in BSI to upgrade at the same time, otherwise trying to bump it in BSI alone will blow up the BSI build. 😅

Oh shoot... I figured a patch wasn't the way to go since this changed the params for the function. I guess I'll be putting up a number of PRs now.

**Comment by grant-cleary** [comment]
> Oh shoot... I figured a patch wasn't the way to go since this changed the params for the function. I guess I'll be putting up a number of PRs now.

Yeah, I mean I think `feat:` is the most _correct_ choice, but because ifrau is in pre-release, minor releases are treated as breaking changes, which ends up making life a bit more painful. 😞

**Comment by eKoopmans** [comment]
Or do a new hacky commit to do a patch after all... would probably work, but we might want to find a way to un-publish this minor release.

**Pull request merged**
