### PR TITLE
send error message for an unknown handler rather than silently ignori…

### PR DESCRIPTION
**Pull request by mdgbayly**
…ng as causes client to hang.

When adding the new onRequest handler for sending intl config overrides, I wanted to make it so that our FRA could be backwards compatible with LMS instances that do not have this handler deployed.

Maybe there is a good reason for silently ignoring unknown handlers, and generally you would not configure a FRA version in an LMS that does not support the FRA. But we usually get FRA updates out much more quickly than LMS updates and so it would be annoying to not be able to test new versions of the FRA in an older LMS.

By sending an error response we can code our FRA to check for a rejected promise when asking for the intl object.  Without this fix, our FRA just hangs and I wasn't sure if there was any other way to conditionally check for the existence of the handler.

### CODE REVIEW

**Comment by omsmith** [comment]
_.eslintignore_ is actually a symlink to _.gitignore_ (`ln -s .gitignore .eslintignore`). I was under the impression that continues to work on Windows. If not, I would just copy it / put all the correct things in.

**Comment by omsmith** [comment]
Try `mkdir dist && mkdir dist/ifrau`? The `cd` might be causing issues with the working directory being incorrect for the rest of the build. (alternatively maybe add a `cd ..` if that doesn't work)

**Comment by omsmith** [comment]
Cautiously labeled as semver-major

**Comment by mdgbayly** [comment]
Regarding .eslintignore symlink - aha, that explains it.  No, I don't think Git for windows still has any good support for symlinks.  I just see eslintignore as a file with .gitignore as the file contents.

http://stackoverflow.com/questions/11662868/what-happens-when-i-clone-a-repository-with-symlinks-on-windows

**Comment by mdgbayly** [comment]
Regarding mkdir dist && mkdir dist/ifrau
I tried that syntax but didn't like it either, which was why I tried using cd.  But then got other issues in Travis. I thought that might be because of the cd but I think it was probably just the eslintignore issue still so I might try putting back the cd provided it doesn't break things for travis.

**Comment by mdgbayly** [comment]
Regarding the main solution, I think I like your solution better as I wan't keen on the fact that my solution involved throwing an error which was going to be caught by the catch below.

**Comment by mdgbayly** [comment]
Updated based on your comments.  Not had much experience defining custom Error types before so let me know if it should be different.  I originally included a stack trace in there which I'd seen in some examples, but made it difficult to test, so took it out...

**Comment by dlockhart** [comment]
This LGTM, @omsmith is this what you had in mind?

**Comment by omsmith** [comment]
Yep - except I would use _inherits_ (https://github.com/Brightspace/ifrau/blob/master/src/port/requests.js#L31)

**Comment by omsmith** [comment]
LGTM otherwise as well.

**Comment by mdgbayly** [comment]
Updated RequestTypeError to use inherits.

Wondering it this needs to be semver-major? Conceptually it doesn't really change any contracts does it? It's just that you now get a response when you request something that does not exist, whereas before you didn't?

**Comment by omsmith** [comment]
Might not be, but being cautious. Would perhaps have to audit _ifrau_ usage a bit. Code like below could be in use, which would change the experience. It's just easier to bump the major to make sure that doesn't happen.

Doesn't super matter to me though, @dlockhart @dbatiste ?

```js
function throwErrorModalAndSaySorry() {}

new Client()
  .connect()
  .then(client => {
    client
      .request('thingWhichDoesntExistAndDoesntActuallyMatter')
      .then(...)
      .catch(throwErrorModalAndSaySorry);
    client
      .request('otherStuff')
      .then(...);
  });
```

**Comment by dlockhart** [comment]
Yeah I'd rather be safe than sorry and just bump the major version.

**Comment by mdgbayly** [comment]
ok - doesn't matter to me either really...

in your example, though, I think that's the kind of code that doesn't work at the moment?
i.e. this promise never resolves does it? I could be totally missing the point here...

```
client
      .request('thingWhichDoesntExistAndDoesntActuallyMatter')
```

**Comment by omsmith** [comment]
Right, it's requesting something that doesn't strictly matter to the overall user experience, and would never resolve, but the rest of the app already works. In this example, if an error is thrown, what was previously not effecting user experience, the application instead says "sorry, something is wrong" and doesn't let the user proceed.

I'm not saying this app exists, but I definitely believe that it perhaps could (and not every application is being developed day-to-day in order to notice).

**Comment by mdgbayly** [comment]
ah, ok - i see what you are saying ... sure - sounds good.

**Comment by mdgbayly** [comment]
@omsmith @dlockhart 
Any thoughts on whether we should attempt to push this out?

It may cause issues for us as we try and add ifrau services for the html editor stuff, as we'll need to make sure we only configure our updated FRA against LMSs that have the new services deployed.

No big deal I guess, but I was thinking I could also use the absence of a service in an LMS to indicate an action is not allowed.  Instead I'm having to add additional 'enabled' ops on each service to indicate that. Maybe that is clearer anyway, but silently swallowing calls and leaving promises hanging still seems like a big limitation to me.

I guess the work is in co-ordinating an update in the LMS with other FRAs if any are affected.

I took a quick look at my dev env config and it seems like we have very few iframe FRAs currently:

"saml-configuration": "https://s.brightspace.com/apps/saml-configuration/0.9.9/appconfig.json"

"manage-extensibility": "https://s.brightspace.com/apps/manage-extensibility/dev/299e804b1d8f42e8a00a9aab8c76b1c3dd5c7ce5/appconfig.json"

"urn:d2l:fra:class:activity-outcomes-assess-fra": "https://s.brightspace.com/apps/activity-outcomes-assess-fra/dev/4edaa79f08a788b8f625ba4605099e62ec30f87b/appconfig.json"

I'm happy to do the legwork to review them for issues if we could agree that we'll release this PR once we have the all clear.

Cheers
Martin

**Comment by dlockhart** [comment]
@mdgbayly yeah I'm good getting this in, especially if we're doing a major semver version bump.

**Pull request merged**
