### PR TITLE
DE41586 - allow autoplay

### PR DESCRIPTION
**Pull request by maggiesazio**
We have a problem with an LTI tool launching in Lessons where the embedded video can't play without this

### CODE REVIEW

**Review by dlockhart — APPROVED** [review]

**Comment by dlockhart** [comment]
`ifrau` does manual releases right now, so you may want to include the version bump in `package.json` as part of this so you can easily create a GH release after this merges.

**Comment by maggiesazio** [comment]
> `ifrau` does manual releases right now, so you may want to include the version bump in `package.json` as part of this so you can easily create a GH release after this merges.

How exactly does releasing this work? Do I just bump the version in the file and manually create a tag? I saw that there is a tag already for v0.34.0 so I guess I should bump this to 0.35.0

**Comment by dlockhart** [comment]
Yeah it looks like it wasn't done properly last time. My suggestion would be to increase it to `0.35.0` in `package.json` in this PR, merge that, and then create a release in the GitHub UI -- which will create a tag. That subsequent CI run will see the tag and publish to NPM.

**Comment by dlockhart** [comment]
This has motivated me -- after you're done I'm going to switch this to use all our new semantic-release and GitHub Actions things.

**Pull request merged**
