### PR TITLE
[WIP] add syntax for host plugins

### PR DESCRIPTION
**Pull request by omsmith**
@dlockhart 

Random thought

```js
import { Host } from 'ifrau';
import { host as jwtHost } from 'frau-jwt';

const host = new Host()
  .using(jwtHost)
  .connect()
  // ...
  ;
```

```js
export host function jwtHost (host) {
  host.onRequest('foo', 'bar');
}
```

### CODE REVIEW

**Comment by omsmith** [comment]
Doesn't need to be anything like this at all, just thinking out loud

**Comment by dlockhart** [comment]
Love it. I was wanting a way to allow FRAs to also do a bit of wire-up within Brightspace (event/request/service handlers) before their app gets initialized, and this works for that as well.

**Comment by dbatiste** [comment]
Thinking out loud too.  Wondering if there should be an API for the Host that provides hooks for the relevant life cycle events for wire-up.  Thinking along the lines of what @dlockhart said:

```
export function myPlugin ( host ) {
  host.onConnect( ()=> host.registerService(...) );
}
```

**Comment by dlockhart** [comment]
I would expect that the `using(myPlugin)` calls would have to happen before the initial `connect` call. Registering services after the initial connection has been made likely isn't something we want.

**Comment by omsmith** [comment]
@dlockhart unless of course the client could negotiate for services to be available, which the host would dynamically load and make available!

...lets table that tough

**Comment by dlockhart** [comment]
Haha yes... let's.

**Comment by dbatiste** [comment]
I hadn't put much thought into the specific phase of the connection where the service registration should occur - just that plug-ins might need to do different things at different points in time, and requiring the exported function to be specific to the initialization phase is a bit limiting.  For example, if the plug-in required some tear-down (assuming it could have some state), we'd need to expose something else, and at that point I'd probably want the API for wire-up to be consistent.  It's difficult to know all the different types of functions plugins might serve, so I'd don't have a specific use-case - again, just thinking out loud.  :)

**Pull request closed without merging**
