### PR TITLE
(refact) Move back to ES5

### PR DESCRIPTION
**Pull request by omsmith**
```
omsmith osmith-ubuntu-t1700 | Fri Oct 23 at 11:24:41 | git master
/home/omsmith/dev/ifrau ~ git checkout master ^C
omsmith osmith-ubuntu-t1700 | Fri Oct 23 at 11:24:48 | git master
/home/omsmith/dev/ifrau ~ npm run browserify && ls -al dist

> ifrau@0.10.1 prebrowserify /home/omsmith/dev/ifrau
> rimraf dist && mkdir dist && npm run transpile


> ifrau@0.10.1 pretranspile /home/omsmith/dev/ifrau
> rimraf lib


> ifrau@0.10.1 transpile /home/omsmith/dev/ifrau
> babel src --optional runtime --out-dir lib

src/client.js -> lib/client.js
src/host.js -> lib/host.js
src/index.js -> lib/index.js
src/plugins/iframe-resizer.js -> lib/plugins/iframe-resizer.js
src/plugins/sync-font.js -> lib/plugins/sync-font.js
src/plugins/sync-lang.js -> lib/plugins/sync-lang.js
src/plugins/sync-title.js -> lib/plugins/sync-title.js
src/port.js -> lib/port.js
src/transform-error.js -> lib/transform-error.js

> ifrau@0.10.1 browserify /home/omsmith/dev/ifrau
> browserify -g uglifyify -s ifrau ./lib/index.js > ./dist/ifrau.js

total 88
drwxrwxr-x 2 omsmith omsmith  4096 Oct 23 11:24 .
drwxrwxr-x 9 omsmith omsmith  4096 Oct 23 11:24 ..
-rw-rw-r-- 1 omsmith omsmith 69726 Oct 23 11:24 ifrau.js
omsmith osmith-ubuntu-t1700 | Fri Oct 23 at 11:24:56 | git master
/home/omsmith/dev/ifrau ~ git checkout es5 
Switched to branch 'es5'
omsmith osmith-ubuntu-t1700 | Fri Oct 23 at 11:25:04 | git es5
/home/omsmith/dev/ifrau ~ npm run browserify && ls -al dist

> ifrau@0.10.1 prebrowserify /home/omsmith/dev/ifrau
> rimraf dist && mkdir dist


> ifrau@0.10.1 browserify /home/omsmith/dev/ifrau
> browserify -g uglifyify -s ifrau ./src/index.js > ./dist/ifrau.js

total 60
drwxrwxr-x 2 omsmith omsmith  4096 Oct 23 11:25 .
drwxrwxr-x 9 omsmith omsmith  4096 Oct 23 11:25 ..
-rw-rw-r-- 1 omsmith omsmith 43474 Oct 23 11:25 ifrau.js
```

### CODE REVIEW

**Comment by omsmith** [comment]
Moved the "private but public" props to be prefixed by `_`, since it's more idiomatic at this point, which is why there's test changes.

Tests are still run with babel, to minimize the change there.

**Comment by omsmith** [comment]
Soo, yeah. Was thinking about how large ifrau is, and with it getting bundled into consumers and whatnot. So figured this would make it smaller, which is true.

As a follow-up, i would add 2 files to allow `require('ifrau/client')` and `require('ifrau/host')`, to avoid clients from pulling in host based code (such as iframe resizer).

**Comment by dbatiste** [comment]
I've briefly looked at this a bit.  Good to see babel-runtime is gone - that was a sizable contributor to ifrau.  I recall the iframe-resizer being a significant contributor to the size of ifrau.  It is sizable enough for me to question whether we ought to use it.  I know there were a couple of issues it helped solve, presumably we were ok with the size given the benefit... ?

**Comment by omsmith** [comment]
Yeah, iframe-resizer is pretty big. It's handy enough for the exact moment. My thought there would be to force consumers to opt into it, and not by an option (they have to explicitly require it), that way it's not part of the normal bundle.

On the _AppLoader/iFrameApp.js_ side, we could avoid loading it if we're not auto-resizing. Something like...

```js
var plugins = [
  'ifrau/sync-font',
  'ifrau/sync-lang',
  'ifrau/sync-title'
];

if (options.autoResize) {
  plugins.push('ifrau/iframe-resizer');
}

Promise.all([
  System.load('ifrau/host'),
  plugins.map(System.load)
]).then(function(Host, plugins) {
  var host = new Host();
  plugins.forEach(host.use);

  host.connect() // ...
});
```

**Comment by omsmith** [comment]
That said. Another other PR

**Comment by dlockhart** [comment]
Looks good @omsmith, thanks for converting this. Poor ES6.

**Pull request merged**
