### PR TITLE
Allow event registry anytime

### PR DESCRIPTION
**Pull request by dlockhart**

### CODE REVIEW

**Comment by omsmith** [comment]
Maybe we still want to warn (use the debug log) the first time?

"You've attached event handlers after connecting, you may have missed some events"

**Comment by dlockhart** [comment]
Yeah I thought about that... really it's like `addEventListener`, if you add an `onclick` event listener after the user clicked, you probably knew what you were doing? I dunno. I have a legit case where something downstream becomes interested in events, but maybe that's a symptom of me doing it wrong.

**Comment by dbatiste** [comment]
I am guessing there's something you want to add afterwards?  I second Owen's suggestion - this could be pretty frustrating if they get it in the wrong order.

**Comment by dlockhart** [comment]
I've added a warning as suggested.

**Pull request merged**
