### PR TITLE
Fixing connect bug in IE

### PR DESCRIPTION
**Pull request by mikepaulsond2l**
IE failed to client connect with "ReferenceError: 'Promise' is undefined"

### CODE REVIEW

**Comment by omsmith** [comment]
Well, shoot. I'll publish a new version. Can you do a version bump in AppLoader?

**Comment by mikepaulsond2l** [comment]
@omsmith I'm not familiar with AppLoader, I just discovered this issue with our content service frapp. If you point me to the repo then I can bump the version though.

**Comment by omsmith** [comment]
Core/AppLoader in git.dev. `config/infrastructure` I think? I'm OOO for the morning so can't look it up. @dlockhart should know if you can't find it.

**Comment by dlockhart** [comment]
Yep:
http://search.dev.d2l/source/xref/LSOne/AppLoader/_config/Infrastructure/D2L.LP.AppLoader.IFrame.config.json

**Comment by mikepaulsond2l** [comment]
Got it, thanks!

**Pull request merged**
